#!/bin/bash

# 定义目标文件路径
TARGET_FILE="/etc/apt/sources.list.d/sileo.sources"

# 创建目录路径（如果不存在）
mkdir -p "$(dirname "$TARGET_FILE")"

# 检查文件是否存在，不存在则创建
if [[ ! -f "$TARGET_FILE" ]]; then
    touch "$TARGET_FILE"
fi

# 追加配置内容到文件
cat <<EOF >> "$TARGET_FILE"
Types: deb
URIs: https://ad-ios.github.io/ad/
Suites: AD
Components: main

EOF
