#!/bin/bash
set -e

Cleanup_old_files() {
    echo "Cleaning up the old version of vnodebypass documents..."
    
    rm -rf /var/jb/Applications/vnodebypass.app/
    rm -rf /var/jb/Library/ControlCenter/Bundles/VBModule.bundle/
    rm -f /var/jb/Library/MobileSubstrate/DynamicLibraries/vnodebypassnext.plist
    rm -f /var/jb/usr/bin/vnodebypass
    # rm -f /var/jb/usr/share/vnodebypass/hidePathList.plist
    
    echo "The old version has been cleaned up."
}

case "$1" in
    install|upgrade)

        Cleanup_old_files
        ;;
    *)

        ;;
esac

exit 0